# -*- coding: utf-8 -*-
"""T5 DAY 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dfbCiE1vzoNPWBOkzaLnaa0YjH6rsjVA
"""

r=int(input())

for i in range(r):
    for j in range(r):
        print("*", end=" ")
    print()

n = int(input())

for i in range(n):
    for j in range(n):
        if i==0 or i==n-1 or j==0 or j==n-1:
            print("*", end=" ")
        else:
            print(" ", end=" ")
    print()

n=int(input())
for i in range(n):
  for j in range(n):
    if i==0 or i==n-1 or (i+j==n-1):
      print("*",end=" ")
    else:
      print(" ",end=" ")
  print()

n=int(input())
for i in range(n):
  for j in range(n):
    if i==0 or i==n-1 or i==j:
      print("*",end=" ")
    else:
      print(" ",end=" ")
  print()

n=int(input())
for i in range(1,n+1):
  for j in range(i):
    print("*",end=" ")
  print()

n=int(input())
for i in range(n,0,-1):
  for j in range(i):
    print("*",end=" ")
  print()

n = int(input("enter the matrix size"))
num=1
for i in range(1,n+1):
    for j in range(i):
        print(num, end=" ")
    num+=1
    print("\n")

mobile="9000055050"
masked=mobile[0:2]+"**"+mobile[-2:]
print(masked)

song="shape OF you"
artist="ed ShEERAN"
formatted=f"{song.title()} - {artist.title()}"
print(formatted)

location=" chenai central"
fixed_location=location.replace("chenai","chennai")
print(fixed_location)

message="your uber bookin ID:UB12345. please keep it safe"
booking_id=message.split(":")[1].split(".")[0]
print(booking_id)

msg="use ZOMATO100 to get Rs.100 off on your first order!"
if "ZOMATO100" in msg:
  print("Offer Applied")

feedback="the driver was polite and the ride was smooth"
print(feedback.find("polite"))

fullname = "Kolli Divya Sudha"
initials = "".join(word[0].upper() for word in fullname.split())
print(initials)

fullname = "Divya Sudha"

initials = ""
for word in fullname.split():
    initials += word[0]

print(initials)

dirty_input=" divya sudha "
cleaned=dirty_input.strip()
print(cleaned)

feedback_msg="hello good morning"
count=len(feedback_msg.split())
print(count)

user_name=input("enter the user name")
password=input("enter the password")
if user_name=="admin" and password=="!234":
  print("login successful")
else:
  print("invalid username and password")

marks=int(input())
attendance=int(input())
if(marks>=50 and attendance>=75):
  print("elgible for exam")
else:
  print("not eligible for exam")

recharge = int(input())
data_balance = float(input())

if recharge == 399 and data_balance > 2:
    data_balance += 2
    print("Bonus applied")
    print("Total data:", data_balance, "GB")
else:
    print("No bonus")
    print("Data:", data_balance, "GB")

bill = float(input())
vip = input().lower()
day = input().lower()

if bill > 1000 and vip == "gold" and day in ["saturday", "sunday"]:
    print("Customer gets 20% discount")
else:
    print("No discount")

correct_password = "2310"
attempts = 0
while attempts < 3:
    password = input("Enter your password:")
    if password == correct_password:
        print("Login successful")
        break
    else:
        print("Wrong password")
        attempts += 1
if attempts == 3:
    print("Account blocked")

def print_data(**kwargs):
  for key,value in kwargs.items():
    print(f"{key}: {value}")
print_data(name="Divya",age=20)

cart = []
while True:
    item = input("Enter item: ")
    if item == "done":
        break
    cart.append(item)
print("Final Cart:", cart)

def create_profile(**kwargs):
  profile={}
  for key,value in kwargs.items():
    profile[key]=value
    print(profile)
  create_profile(name="divya",age=20,email="divya@gmail.com",)

def profile_generator(**kwargs):
    profile_text = ""
    for key, value in kwargs.items():
        profile_text += f"{key.capitalize():<12}: {value}\n"
    return profile_text

name = input("Enter your full name: ").strip()
age = input("Enter your age: ").strip()
department = input("Enter your department: ").strip()
college = input("Enter your college: ").strip()
email = input("Enter your email: ").strip()

result = profile_generator(
    name=name,
    age=age,
    department=department,
    college=college,
    email=email
)

print(result)

def greet(name="hyderabad"):
  print(f"welcome to {name}")
greet()

def total_trip_bill(*args):
    total = 0
    for amount in args:
        total += amount
    return total


def show_trip_summary(**kwargs):
    phone = kwargs["phone"]
    masked_phone = phone[:2] + "******" + phone[-2:]

    print("\nTRIP SUMMARY")
    print("Name:", kwargs["name"].title())
    print("Age:", kwargs["age"])
    print("Phone:", masked_phone)

    print("\nPlaces Visited:")
    for place in kwargs["places"]:
        print("-", place)

    print("\nRestaurants:")
    for restaurant in kwargs["restaurants"]:
        print("-", restaurant)

    print("\nBills:")
    count = 1
    for amount in kwargs["bills"]:
        print("Bill", count, ": Rs.", amount)
        count += 1

    print("\nTotal Trip Bill: Rs.", kwargs["total"])


name = input("Enter name: ").strip()
age = input("Enter age: ").strip()
phone = input("Enter phone: ").strip()

places = ["Hyderabad", "Chennai", "Goa"]
restaurants = ["Paradise", "Blue Sea", "Sindhu"]
bills = [1200, 890, 450, 2000, 150, 600, 3000, 480, 900, 750]

total = total_trip_bill(*bills)

show_trip_summary(
    name=name,
    age=age,
    phone=phone,
    places=places,
    restaurants=restaurants,
    bills=bills,
    total=total
)

def travel_profile(**kwargs):
    profile = {}
    for key, value in kwargs.items():
        profile[key] = value
    return profile

def bill_calculator(*args):
    total = 0
    for amount in args:
        total += amount
    return total

name = input("Enter name: ").strip()
email = input("Enter email: ").strip()
phone = input("Enter phone number: ").strip()
age = input("Enter age: ").strip()
place = input("Enter travel location: ").strip()
days=input("Enter number of trip days:").strip()

food = float(input("Enter food expense: "))
travel = float(input("Enter travel expense: "))
restaurant = float(input("Enter restaurant expense: "))
stay = float(input("Enter stay expense: "))

masked_phone = phone[:2] + "******" + phone[-2:]

user_profile = travel_profile(
    name=name,
    email=email,
    phone=masked_phone,
    age=age,
    location=place,
    trip_days=days
)

total_bill = bill_calculator(food, travel, restaurant, stay)

print("\nTraveller Profile")
for key, value in user_profile.items():
    print(f"{key}: {value}")

print(f"\nTotal Expenditure: ₹{total_bill}")